#!/bin/sh

K3S_VERSION=v1.17.0+k3s.1


mkdir -p bin
curl -RLo bin/k3s https://github.com/rancher/k3s/releases/download/$K3S_VERSION/k3s && chmod +x bin/k3s
ln -sf k3s bin/kubectl

# docker-machine ssh tce-load -w socat.tcz
for tcz in openssl.tcz readline.tcz ncursesw.tcz socat.tcz; do
     curl -RLo tcz/$tcz http://repo.tinycorelinux.net/10.x/x86_64/tcz/$tcz; done

sha256sum -c SHA256SUM.txt

( cd tcz && md5sum -c *.md5.txt )

