#!/bin/sh

tce-load -i socat.tcz ipset.tcz

sudo -E -b k3s server \
	--container-runtime-endpoint unix:///var/run/docker/containerd/containerd.sock \
        --no-deploy traefik --no-deploy servicelb --no-flannel --disable-network-policy \
        --write-kubeconfig /home/docker/.kube/config \
	--log /var/log/k3s.log

sudo chown docker:staff /home/docker/.kube/config

# wait for apiserver
sleep 10

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml

# ugly hack for CNI
sudo mkdir -p /opt/cni && sudo ln -s /var/lib/rancher/k3s/data/c67259f824ace42864ead7655dbe15a5b736ad91050498224cd42f777416d8dd/bin /opt/cni/bin
