#!/bin/sh

tce-load -i socat.tcz

sudo -E -b k3s server \
	--container-runtime-endpoint unix:///var/run/docker/containerd/containerd.sock \
        --no-deploy traefik --no-deploy servicelb \
        --write-kubeconfig /home/docker/.kube/config \
	--log /var/log/k3s.log

sudo chown docker:staff /home/docker/.kube/config
